spring.application.name=source-share

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/cloud_disk?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf-8
spring.datasource.username=czl
spring.datasource.password=1522518cuI!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
